# Generated by Django 4.0.3 on 2022-06-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('inspectorName', models.CharField(max_length=50)),
                ('itemsOk', models.IntegerField()),
                ('issuesWarningCount', models.IntegerField()),
                ('issuesCriticalCount', models.IntegerField()),
                ('company', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
